---
# Example Playbook: cisco.intersight.intersight_bios_policy
# Runs on localhost since policies are only configured once
# Author: Surendra Ramarao (@CRSurendra)
- name: Configure BIOS Policy
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    # Create an anchor for api_info that can be used throughout the file
    api_info: &api_info
      # if api_key vars are omitted, INTERSIGHT_API_KEY_ID, INTERSIGHT_API_PRIVATE_KEY,
      # and INTERSIGHT_API_URI environment variables used for API key data
      api_private_key: "{{ api_private_key | default(omit) }}"
      api_key_id: "{{ api_key_id | default(omit) }}"
      api_uri: "{{ api_uri | default(omit) }}"
      validate_certs: "{{ validate_certs | default(omit) }}"
      state: "{{ state | default('present') }}"
    # Organization name
    org_name: Cloudera-SZR-Org
  tasks:
    - name: Configure BIOS Policy
      cisco.intersight.intersight_bios_policy:
        <<: *api_info
        organization: "{{ org_name }}"
        name: SUR_BIOS
        description: BIOS policy for lab use
        tags:
          - Key: Site
            Value: RCDN
        cpu_energy_performance: performance
