---
# Example Playbook: cisco.intersight.intersight_virtual_ethernet_interface
# Runs on localhost since policies are only configured once
# Author: Surendra Ramarao (@CRSurendra)
- hosts: localhost
  connection: local
  collections:
    - cisco.intersight
  gather_facts: false
  vars:
    # Create an anchor for api_info that can be used throughout the file
    api_info: &api_info
      # if api_key vars are omitted, INTERSIGHT_API_KEY_ID, INTERSIGHT_API_PRIVATE_KEY,
      # and INTERSIGHT_API_URI environment variables used for API key data
      api_private_key: "{{ api_private_key | default(omit) }}"
      api_key_id: "{{ api_key_id | default(omit) }}"
      api_uri: "{{ api_uri | default(omit) }}"
      validate_certs: "{{ validate_certs | default(omit) }}"
      state: "{{ state | default('present') }}"
    mac_pool: cloudera-SZR-macpool
    eth_adapter_policy: TEST_EAP
    eth_network_policy: TEST_ENP
    eth_qos_policy: TEST_EQOS
    lc_policy: SUR_LCP1

  tasks:
    - name: Configure Virtual Ethernet Interface
      intersight_virtual_ethernet_interface:
        <<: *api_info
        name: eth0
        tags:
          - Key: Site
            Value: RCDN
        cdn:
          - source: vnic
        failover_enabled: false
        mac_address_type: POOL
        mac_pool: "{{ mac_pool }}"
        placement:
          - auto_pci_link: false
            auto_slot_id: false
            switch_id: A
        eth_adapter_policy: "{{ eth_adapter_policy }}"
        eth_network_policy: "{{ eth_network_policy }}"
        eth_qos_policy: "{{eth_qos_policy}}"
        lan_connectivity_policy: "{{lc_policy}}"


       
        


        

        
