---
#
# Summary: Auto generate (or update) the Ansible inventory file with all servers (Name and Moid or each discovered server)
#
# The hosts group used is provided by the group variable or defaulted to 'Intersight'.
# You can specify a specific host (or host group) on the command line:
#   ansible-playbook ... -e group=<your host group>
#   e.g., ansible-playbook server_profiles.yml -e group=TME_Demo
#
# This playbook only runs once (and not for each server in the inventory), but the hosts group is used to get API key info
#
- name: Auto generate (or update) the Ansible inventory file with all servers
  hosts: "{{ group | default('Intersight') }}"
  connection: local
  gather_facts: false
  vars:
    # Create an anchor for api_info that can be used throughout the file
    api_info: &api_info
      # if api_key vars are omitted, INTERSIGHT_API_KEY_ID, INTERSIGHT_API_PRIVATE_KEY,
      # and INTERSIGHT_API_URI environment variables used for API key data
      api_private_key: "{{ api_private_key | default(omit) }}"
      api_key_id: "{{ api_key_id | default(omit) }}"
      api_uri: "{{ api_uri | default(omit) }}"
      validate_certs: "{{ validate_certs | default(omit) }}"
      state: "{{ state | default(omit) }}"
    # Change filepath if you want to update a different inventory file
    filepath: "{{ inventory_file }}"
    # Change host_group if you want to use another group name for your servers in the created inventory
    host_group: Intersight_Servers
  tasks:
    # Enclose tasks in a block that is only run once
    - name: Get servers and place in inventory file
      delegate_to: localhost
      run_once: true
      block:
        # Find all servers
        - name: Get all servers
          cisco.intersight.intersight_info:
            <<: *api_info
            server_names:
          register: all_results
        # Place the servers in a group in the file
        - name: Print inventory filepath
          ansible.builtin.debug:
            msg: Inventory filepath "{{ filepath }}"
        - name: Add host group to file
          ansible.builtin.lineinfile:
            path: "{{ filepath }}"
            line: "[{{ host_group }}]"
            mode: '0644'
            create: true
        # Update servers in the file
        - name: Update servers in the file
          ansible.builtin.lineinfile:
            path: "{{ filepath }}"
            insertafter: "^\\[{{ host_group }}\\]"
            regexp: "^{{ item.Name }} serial={{ item.Serial }} "
            # Each line of the inventory has the following:
            line: >-
              {{ item.Name }} serial={{ item.Serial }} server_moid={{ item.Moid }} model={{ item.Model }} mode={{ item.ManagementMode }}
              object_type={{ item.SourceObjectType | regex_replace('compute.') }}
            mode: '0644'
            create: true
          loop: "{{ all_results.intersight_servers }}"
          loop_control:
            label: "{{ item.Name }}"
          when: all_results.intersight_servers is defined
